name: Pages quick test
on: workflow_dispatch

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Create site
        run: |
          mkdir -p site
          echo '<!doctype html><meta charset="utf-8"><title>OK</title><h1>GitHub Pages: OK ✅</h1>' > site/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy
        uses: actions/deploy-pages@v4
