name: Pages quick test
on: workflow_dispatch
permissions:
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create simple site
        run: |
          mkdir -p site
          echo '<!doctype html><meta charset="utf-8"><title>OK</title><h1>Pages OK</h1>' > site/index.html
      - uses: actions/upload-pages-artifact@v3
        with: { path: site }
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
